name: Sync Notebooks to Markdown Repo

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  sync-to-md-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Notebooks Repo
        uses: actions/checkout@v4
        with:
          repository: cal-icor/textbook.notebooks
          path: notebooks_repo
          fetch-depth: 0
          
      - name: Identify Added Notebooks
        id: detect-new-notebooks
        run: |
          cd notebooks_repo
          git diff --name-status HEAD^ HEAD | grep '^A' | awk '{print $2}' | grep '\.ipynb$' > new_notebooks.txt || true
          echo "New Notebooks:"
          cat new_notebooks.txt || echo "No new notebooks found."
          echo "NOTEBOOKS=$(cat new_notebooks.txt | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Convert Notebooks to MyST
        run: |
          pip install jupytext
          cd notebooks_repo
          for nb in $NOTEBOOKS; do
            jupytext "$nb" --to myst
          done

      - name: Checkout Markdown Repo
        uses: actions/checkout@v4
        with:
          repository: cal-icor/textbook
          path: md_repo
          token: ${{ secrets.TEXTBOOK_REPO_PAT }}

      - name: Sync requirements.txt and _toc.yml to modules/
        run: |
          cp notebooks_repo/requirements.txt md_repo/modules/requirements.txt
          cp notebooks_repo/_toc.yml md_repo/modules/_toc.yml

      - name: Move Converted MyST Files to Modules
        run: |
          cd notebooks_repo
          for nb in $NOTEBOOKS; do
            md_file="${nb%.ipynb}.md"
            mv "$md_file" ../md_repo/modules/
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "jonathanferrari"
          git config --global user.email "jonathanferrari@berkeley.edu"

          git add modules/requirements.txt modules/_toc.yml
          git add modules/*.md  # Add all converted MyST files

          if git diff --staged --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Sync updates: modules/requirements.txt, modules/_toc.yml, and new MyST notebooks"
            git push
          fi
